apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "ktor-sorlandet"
  namespace: "utvikling-admin"
  labels:
    "team": "utvikling-admin"
spec:
  image: {{ image }}
  liveness:
    path: "/internal/isAlive"
    port: 8080
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/internal/isReady"
    port: 8080
    initialDelay: 20
    timeout: 60
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: "512Mi"
    requests:
      cpu: "50m"
      memory: "200Mi"
  ingresses:
    - "https://ktor-sorlandet.intern.dev.nav.no"
